// This file is auto-generated by next-intl, do not edit directly.
// See: https://next-intl.dev/docs/workflows/typescript#messages-arguments

declare const messages: {
  "Header": {
    "login": "Login",
    "logout": "Logout",
    "items": "Items",
    "userInfoGreeting": "Welcome, {name}"
  },
  "RootPage": {
    "login": "Login",
    "items": "Items"
  },
  "ItemsPage": {
    "title": "Items",
    "description": "You can enjoy the beautiful photos",
    "prevNavButton": "Prev",
    "nextNavButton": "Next",
    "pageNotFoundTitle": "Page Not Found",
    "pageNotFoundDescription": "Selected item not exists",
    "pageNotFoundGoToItemsPageButton": "Go to the Items Page",
    "cartDetailsButton": "Details"
  },
  "ItemPage": {
    "title": "Details",
    "previousPageButton": "Go to the Previous Page",
    "notFoundBackButton": "Go to the Items Page",
    "photoId": "Photo ID",
    "photoAlbumId": "Album ID",
    "photoTitle": "Title"
  },
  "SignPage": {
    "signInTab": "Sign In",
    "signUpTab": "Sign Up",
    "nameLabel": "Name",
    "nameInputPlaceholder": "Name",
    "emailLabel": "Email address",
    "emailInputPlaceholder": "Enter your email address",
    "passwordLabel": "Password",
    "confirmPasswordLabel": "Confirm password",
    "showPasswordText": "Show password",
    "hidePasswordText": "Hide password",
    "signInButton": "Sign In",
    "signUpButton": "Sign Up",
    "requiredErrorMessage": "Required",
    "incorrectEmailErrorMessage": "Incorrect email format",
    "passwordsAreNotMatchErrorMessage": "Passwords are tor match",
    "minLengthErrorMessage": "Min length is {minLength} symbols"
  }
};
export default messages;